import { Platform, SocialPost } from "./types";

export const TEST_POSTS: SocialPost[] = [
  {
    id: "test-1",
    platform: Platform.YouTube,
    brandName: "BAJI",
    accountName: "@bajilive",
    currency: "BDT",
    creatorName: "Test User",
    postedBy: "Test Admin",
    remarks: "YouTube embed test",
    content: "https://youtu.be/MgY01n03QLU?si=BMNJtNnh3fDRZci0",
    date: new Date().toISOString().split("T")[0],
    createdAt: Date.now(),
    mediaType: "embed",
    category: "Test",
    postType: "VIDEO",
  },
  {
    id: "test-2",
    platform: Platform.Instagram,
    brandName: "JeetBuzz",
    accountName: "@jeetbuzz",
    currency: "BDT",
    creatorName: "Test User",
    postedBy: "Test Admin",
    remarks: "Instagram embed test",
    content:
      "https://www.instagram.com/p/DQ5oWDMjVpA/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==",
    date: new Date().toISOString().split("T")[0],
    createdAt: Date.now(),
    mediaType: "embed",
    category: "Test",
    postType: "IMAGE",
  },
  {
    id: "test-3",
    platform: Platform.FacebookPage,
    brandName: "SIX6S",
    accountName: "@six6s",
    currency: "INR",
    creatorName: "Test User",
    postedBy: "Test Admin",
    remarks: "Facebook page embed test",
    content: "https://www.facebook.com/share/p/16M62rS3Ep/",
    date: new Date().toISOString().split("T")[0],
    createdAt: Date.now(),
    mediaType: "embed",
    category: "Test",
    postType: "LINK",
  },
  {
    id: "test-4",
    platform: Platform.FacebookGroup,
    brandName: "BADSHA",
    accountName: "@badsha",
    currency: "BDT",
    creatorName: "Test User",
    postedBy: "Test Admin",
    remarks: "Facebook group embed test",
    content: "https://www.facebook.com/share/p/1AbcU4mpa8/",
    date: new Date().toISOString().split("T")[0],
    createdAt: Date.now(),
    mediaType: "embed",
    category: "Test",
    postType: "LINK",
  },
  {
    id: "test-5",
    platform: Platform.Pinterest,
    brandName: "TekkaBuzz",
    accountName: "@tekkabuzz",
    currency: "PKR",
    creatorName: "Test User",
    postedBy: "Test Admin",
    remarks: "Pinterest embed test",
    content: "https://pin.it/76q797g08",
    date: new Date().toISOString().split("T")[0],
    createdAt: Date.now(),
    mediaType: "embed",
    category: "Test",
    postType: "IMAGE",
  },
  {
    id: "test-6",
    platform: Platform.TikTok,
    brandName: "BAJI",
    accountName: "@baji_tiktok",
    currency: "BDT",
    creatorName: "Test User",
    postedBy: "Test Admin",
    remarks: "TikTok embed test",
    content:
      "https://www.tiktok.com/@chourmcheuofficial/video/7565525751957687560?is_from_webapp=1&sender_device=pc",
    date: new Date().toISOString().split("T")[0],
    createdAt: Date.now(),
    mediaType: "embed",
    category: "Test",
    postType: "VIDEO",
  },
  {
    id: "test-7",
    platform: Platform.Telegram,
    brandName: "JeetBuzz",
    accountName: "@jeetbuzz_telegram",
    currency: "BDT",
    creatorName: "Test User",
    postedBy: "Test Admin",
    remarks: "Telegram channel test (link-only)",
    content: "https://t.me/jeetbuzzPKpublic/200",
    date: new Date().toISOString().split("T")[0],
    createdAt: Date.now(),
    mediaType: "embed",
    category: "Test",
    postType: "LINK",
  },
];
